add_newline = false

format = """\
  $username\
  $hostname\
  $kubernetes\
  $docker_context\

  $git_branch\
  $git_commit\
  $git_state\
  $hg_branch\

  $aws\
  $golang\
  $nodejs\
  $python\
  $ruby\

  $package\

  $cmd_duration\
  $custom\

  $line_break\

  $directory\
  $git_status\
  $character\
  """

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[character]
symbol = " >"
style_failure = "bold red"
style_success = "bold 6"
error_symbol = " >"
use_symbol_for_status = true

[docker]
symbol = " "

[git_branch]
style = "bold yellow"
symbol = " "

[git_status]
style = "bold fg:6"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = ""
conflicted.value = "☠" 
conflicted.style = "red"
modified.value = "ϟ" 
modified.style = "bold red"
renamed = ""
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = ""
untracked = ""
staged.value = " ++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

