format = """
$directory$git_branch$git_status$fill$cmd_duration$nodejs$python$docker_context$aws
$character"""

[fill]
symbol = " "

[character]
success_symbol = "[❯](#a3be8c)"
error_symbol = "[❯](#bf616a)"

[directory]
style = "#88c0d0 bold"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""
style = "#b48ead"
format = " [\\[$branch\\]]($style)"

[git_status]
format = '( [·](dimmed) $all_status$ahead_behind)'
conflicted = "[!$count](#bf616a) "
ahead = "[⇡$count](#88c0d0) "
behind = "[⇣$count](#bf616a) "
diverged = "[⇕](#bf616a) "
staged = "[+$count](#a3be8c) "
modified = "[!$count](#d08770) "
deleted = "[−$count](#bf616a) "
untracked = "[+$count](#ebcb8b) "
renamed = "[→$count](#a3be8c) "
stashed = "[⚑$count](#b48ead) "

[nodejs]
symbol = ""
style = "#a3be8c"
format = "[node](dimmed) [$version]($style) [·](dimmed) "
detect_files = [".nvmrc", "package.json"]

[python]
symbol = ""
style = "#ebcb8b"
format = "[py](dimmed) [$version]($style)[ \\($virtualenv\\)](#88c0d0) [·](dimmed) "
detect_folders = [".venv"]

[docker_context]
symbol = ""
style = "#81a1c1"
format = "[docker](dimmed) [$context]($style) [·](dimmed) "

[aws]
symbol = ""
style = "#d08770"
format = "[aws](dimmed) [$profile]($style)"
force_display = false

[package]
disabled = true

[cmd_duration]
min_time = 2000
style = "#ebcb8b"
format = "[took](dimmed) [$duration]($style) [·](dimmed) "
