#!/bin/bash

function __aws_alias_switch_profile() {
  if [ -z $1 ]; then  echo "Usage: awsswitch profilename"; return; fi

  exists="$(aws configure get aws_access_key_id --profile $1)"

  if [[ -n $exists ]]; then
    export AWS_DEFAULT_PROFILE=$1;
    export AWS_PROFILE=$1;
    export AWS_REGION=$(aws configure get region --profile $1);

    echo "Switched to AWS Profile: $1";
    echo "\n";
    aws configure list
  fi
}

alias awsprofiles="aws configure list-profiles"
alias awsswitch="__aws_alias_switch_profile"
alias awswho="aws configure list"

alias awsaccounts="aws organizations list-accounts | jq \".Accounts[] | {Id, Name}\""
